### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by MANSHALAMBA** [syxanash/logosweeper#8]
./src/index.js
TypeError: Cannot read property 'forEach' of undefined

Am getting this error on running this app

**Comment by syxanash** [comment]
Hi, try to execute the commands in the following order:
1. `nvm use` will make you use the version of Node suggested to run this app which is the **8.10**
2. `npm install` to install all the dependencies
3. `yarn` to install the dependencies using yarn
4. `yarn start` to run the application

**Comment by syxanash** [comment]
Hope that solved your issue, I'm closing this for the moment.
